## static_territories
UPDATE static_territories SET tr_name_id='Afrika',tr_iso_nr='2' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_id='Oceania',tr_iso_nr='9' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_id='Amerika Utara, Tengah & Selatan',tr_iso_nr='19' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_id='Asia',tr_iso_nr='142' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_id='Eropa',tr_iso_nr='150' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_id='Asia Timur',tr_iso_nr='30' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_id='Asia Tenggara',tr_iso_nr='35' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_id='0',tr_iso_nr='143' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_id='Asia Barat',tr_iso_nr='145' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_id='Eropa Selatan',tr_iso_nr='39' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_id='Eropa Timur',tr_iso_nr='151' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_id='Eropa Utara',tr_iso_nr='154' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_id='Eropa Barat',tr_iso_nr='155' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_id='Amerika Selatan',tr_iso_nr='5' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_id='Amerika Tengah',tr_iso_nr='13' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_id='Amerika Utara',tr_iso_nr='21' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_id='Karibia',tr_iso_nr='29' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_id='Afrika Barat',tr_iso_nr='11' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_id='Afrika Timur',tr_iso_nr='14' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_id='Afrika Utara',tr_iso_nr='15' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_id='Afrika Tengah',tr_iso_nr='17' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_id='Afrika Selatan',tr_iso_nr='18' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_id='Australia dan Selandia Baru',tr_iso_nr='53' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_id='Melanesia',tr_iso_nr='54' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_id='Mikronesia',tr_iso_nr='57' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_id='Polinesia',tr_iso_nr='61' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_id='0',tr_iso_nr='34' WHERE tr_iso_nr='34';


## static_countries
UPDATE static_countries SET cn_short_id='Andorra',cn_iso_2='AD' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_id='Uni Emirat Arab',cn_iso_2='AE' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_id='Afghanistan',cn_iso_2='AF' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_id='Antigua und Barbuda',cn_iso_2='AG' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_id='Anguilla',cn_iso_2='AI' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_id='Albania',cn_iso_2='AL' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_id='Armenia',cn_iso_2='AM' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_id='Antillen Belanda',cn_iso_2='AN' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_id='Angola',cn_iso_2='AO' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_id='Antartika',cn_iso_2='AQ' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_id='Argentina',cn_iso_2='AR' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_id='Amerikan Samoa',cn_iso_2='AS' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_id='Austria',cn_iso_2='AT' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_id='Australia',cn_iso_2='AU' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_id='Aruba',cn_iso_2='AW' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_id='Azerbaijan',cn_iso_2='AZ' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_id='Bosnia dan Herzegovina',cn_iso_2='BA' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_id='Barbados',cn_iso_2='BB' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_id='Bangladesh',cn_iso_2='BD' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_id='Belgia',cn_iso_2='BE' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_id='Burkina Faso',cn_iso_2='BF' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_id='Bulgaria',cn_iso_2='BG' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_id='Bahrain',cn_iso_2='BH' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_id='Burundi',cn_iso_2='BI' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_id='Benin',cn_iso_2='BJ' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_id='Bermuda',cn_iso_2='BM' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_id='Brunei Darussalam',cn_iso_2='BN' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_id='Bolivia',cn_iso_2='BO' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_id='Brasil',cn_iso_2='BR' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_id='Bahama',cn_iso_2='BS' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_id='Bhutan',cn_iso_2='BT' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_id='Pulau Bouvet',cn_iso_2='BV' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_id='Botswana',cn_iso_2='BW' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_id='Belarus',cn_iso_2='BY' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_id='Belize',cn_iso_2='BZ' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_id='Kanada',cn_iso_2='CA' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_id='Kokos (Keeling)',cn_iso_2='CC' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_id='Demokratik Republik Kongo',cn_iso_2='CD' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_id='Republik Afrika Tengah',cn_iso_2='CF' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_id='Kongo',cn_iso_2='CG' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_id='Swiss',cn_iso_2='CH' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_id='Pantai Gading',cn_iso_2='CI' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_id='Kepulauan Cook',cn_iso_2='CK' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_id='Chili',cn_iso_2='CL' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_id='Kamerun',cn_iso_2='CM' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_id='Cina',cn_iso_2='CN' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_id='Kolombia',cn_iso_2='CO' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_id='Kosta Rika',cn_iso_2='CR' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_id='Kuba',cn_iso_2='CU' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_id='Cape Verde',cn_iso_2='CV' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_id='Pulau Christmas',cn_iso_2='CX' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_id='Siprus',cn_iso_2='CY' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_id='Republik Ceko',cn_iso_2='CZ' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_id='Jerman',cn_iso_2='DE' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_id='Djibouti',cn_iso_2='DJ' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_id='Denmark',cn_iso_2='DK' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_id='Dominica',cn_iso_2='DM' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_id='Republik Dominika',cn_iso_2='DO' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_id='Aljazair',cn_iso_2='DZ' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_id='Ekuador',cn_iso_2='EC' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_id='Estonia',cn_iso_2='EE' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_id='Mesir',cn_iso_2='EG' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_id='Sahara Barat',cn_iso_2='EH' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_id='Eritrea',cn_iso_2='ER' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_id='Spanyol',cn_iso_2='ES' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_id='Ethiopia',cn_iso_2='ET' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_id='Finlandia',cn_iso_2='FI' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_id='Fiji',cn_iso_2='FJ' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_id='Kepulauan Falkland',cn_iso_2='FK' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_id='Mikronesien',cn_iso_2='FM' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_id='Kepulauan Faru',cn_iso_2='FO' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_id='Prancis',cn_iso_2='FR' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_id='Gabon',cn_iso_2='GA' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_id='Inggris',cn_iso_2='GB' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_id='Grenada',cn_iso_2='GD' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_id='Georgia',cn_iso_2='GE' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_id='Guyana Perancis',cn_iso_2='GF' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_id='Ghana',cn_iso_2='GH' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_id='Gibraltar',cn_iso_2='GI' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_id='Greenland',cn_iso_2='GL' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_id='Gambia',cn_iso_2='GM' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_id='Guinea',cn_iso_2='GN' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_id='Guadeloupe',cn_iso_2='GP' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_id='Guinea Ekuatorial',cn_iso_2='GQ' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_id='Yunani',cn_iso_2='GR' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_id='Georgia Selatan dan Kepulauan Sandwich Selatan',cn_iso_2='GS' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_id='Guatemala',cn_iso_2='GT' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_id='Guam',cn_iso_2='GU' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_id='Nugini Ekuatorial',cn_iso_2='GW' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_id='Guyana',cn_iso_2='GY' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_id='Hong Kong S.A.R., China',cn_iso_2='HK' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_id='Honduras',cn_iso_2='HN' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_id='Kroasia',cn_iso_2='HR' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_id='Haiti',cn_iso_2='HT' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_id='Hongaria',cn_iso_2='HU' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_id='Indonesia',cn_iso_2='ID' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_id='Irlandia',cn_iso_2='IE' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_id='Israel',cn_iso_2='IL' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_id='India',cn_iso_2='IN' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_id='Britania Ocean Territory',cn_iso_2='IO' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_id='Irak',cn_iso_2='IQ' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_id='Iran',cn_iso_2='IR' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_id='Islandia',cn_iso_2='IS' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_id='Italia',cn_iso_2='IT' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_id='Jamaika',cn_iso_2='JM' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_id='Jordania',cn_iso_2='JO' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_id='Jepang',cn_iso_2='JP' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_id='Kenya',cn_iso_2='KE' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_id='Kirgistan',cn_iso_2='KG' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_id='Kamboja',cn_iso_2='KH' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_id='Kiribati',cn_iso_2='KI' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_id='Komoro',cn_iso_2='KM' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_id='St. Kitts dan Nevis',cn_iso_2='KN' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_id='Korea Utara',cn_iso_2='KP' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_id='Korea Selatan',cn_iso_2='KR' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_id='Kuwait',cn_iso_2='KW' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_id='Kepulauan Cayman',cn_iso_2='KY' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_id='Kazakhstan',cn_iso_2='KZ' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_id='Laos',cn_iso_2='LA' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_id='Lebanon',cn_iso_2='LB' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_id='St. Lucia',cn_iso_2='LC' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_id='Liechtenstein',cn_iso_2='LI' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_id='Sri Lanka',cn_iso_2='LK' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_id='Liberia',cn_iso_2='LR' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_id='Lesotho',cn_iso_2='LS' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_id='Lithuania',cn_iso_2='LT' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_id='Luksemburg',cn_iso_2='LU' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_id='Latvia',cn_iso_2='LV' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_id='Libya',cn_iso_2='LY' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_id='Maroko',cn_iso_2='MA' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_id='Monako',cn_iso_2='MC' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_id='Republik Moldova',cn_iso_2='MD' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_id='Madagascar',cn_iso_2='MG' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_id='Kepulauan Marshall',cn_iso_2='MH' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_id='Macedonia',cn_iso_2='MK' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_id='Mali',cn_iso_2='ML' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_id='Myanmar',cn_iso_2='MM' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_id='Mongolia',cn_iso_2='MN' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_id='Macau',cn_iso_2='MO' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_id='Kepulauan Mariana Utara',cn_iso_2='MP' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_id='Martinique',cn_iso_2='MQ' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_id='Mauritania',cn_iso_2='MR' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_id='Montserrat',cn_iso_2='MS' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_id='Malta',cn_iso_2='MT' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_id='Mauritius',cn_iso_2='MU' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_id='Maladewa',cn_iso_2='MV' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_id='Malawi',cn_iso_2='MW' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_id='Mexico',cn_iso_2='MX' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_id='Malaysia',cn_iso_2='MY' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_id='Mozambik',cn_iso_2='MZ' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_id='Namibia',cn_iso_2='NA' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_id='Caledonia',cn_iso_2='NC' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_id='Niger',cn_iso_2='NE' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_id='Pulau Norfolk',cn_iso_2='NF' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_id='Nigeria',cn_iso_2='NG' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_id='Nikaragua',cn_iso_2='NI' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_id='Belanda',cn_iso_2='NL' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_id='Norwegia',cn_iso_2='NO' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_id='Nepal',cn_iso_2='NP' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_id='Nauru',cn_iso_2='NR' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_id='Pulau Niue',cn_iso_2='NU' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_id='Selandia Baru',cn_iso_2='NZ' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_id='Oman',cn_iso_2='OM' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_id='Panama',cn_iso_2='PA' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_id='Peru',cn_iso_2='PE' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_id='Polinesia',cn_iso_2='PF' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_id='Papua Nugini',cn_iso_2='PG' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_id='Filipina',cn_iso_2='PH' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_id='Pakistan',cn_iso_2='PK' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_id='Polandia',cn_iso_2='PL' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_id='St. Pierre dan Miquelon',cn_iso_2='PM' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_id='Pitcairn',cn_iso_2='PN' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_id='Puerto Rico',cn_iso_2='PR' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_id='Portugal',cn_iso_2='PT' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_id='Palau',cn_iso_2='PW' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_id='Paraguay',cn_iso_2='PY' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_id='Qatar',cn_iso_2='QA' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_id='Reuni',cn_iso_2='RE' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_id='Rumania',cn_iso_2='RO' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_id='Federasi Rusia',cn_iso_2='RU' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_id='Rwanda',cn_iso_2='RW' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_id='Arab saudi',cn_iso_2='SA' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_id='Salomo',cn_iso_2='SB' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_id='Seychelles',cn_iso_2='SC' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_id='Sudan',cn_iso_2='SD' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_id='Swedia',cn_iso_2='SE' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_id='Singapura',cn_iso_2='SG' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_id='St. Helena',cn_iso_2='SH' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_id='Slovenia',cn_iso_2='SI' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_id='Svalbard dan Jan Mayen',cn_iso_2='SJ' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_id='Slovakia',cn_iso_2='SK' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_id='Sierra Leone',cn_iso_2='SL' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_id='San Marino',cn_iso_2='SM' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_id='Senegal',cn_iso_2='SN' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_id='Somalia',cn_iso_2='SO' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_id='Suriname',cn_iso_2='SR' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_id='Sao Tome und Príncipe',cn_iso_2='ST' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_id='El Salvador',cn_iso_2='SV' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_id='Suriah',cn_iso_2='SY' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_id='Swaziland',cn_iso_2='SZ' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_id='Turks dan Caicos',cn_iso_2='TC' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_id='Chad',cn_iso_2='TD' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_id='Perancis Selatan dan Antartika',cn_iso_2='TF' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_id='Togo',cn_iso_2='TG' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_id='Thailand',cn_iso_2='TH' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_id='Tajikistan',cn_iso_2='TJ' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_id='Tokelau',cn_iso_2='TK' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_id='Turkmenistan',cn_iso_2='TM' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_id='Tunisia',cn_iso_2='TN' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_id='Tonga',cn_iso_2='TO' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_id='Timor Timur',cn_iso_2='TL' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_id='Turki',cn_iso_2='TR' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_id='Trinidad dan Tobago',cn_iso_2='TT' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_id='Tuvalu',cn_iso_2='TV' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_id='Taiwan',cn_iso_2='TW' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_id='Tanzania',cn_iso_2='TZ' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_id='Ukraina',cn_iso_2='UA' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_id='Uganda',cn_iso_2='UG' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_id='American Pasifik',cn_iso_2='UM' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_id='Amerika Serikat',cn_iso_2='US' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_id='Uruguay',cn_iso_2='UY' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_id='Uzbekistan',cn_iso_2='UZ' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_id='Vatikan',cn_iso_2='VA' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_id='St. Vinsent dan Grenadines',cn_iso_2='VC' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_id='Venezuela',cn_iso_2='VE' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_id='Inggris, Kepulauan Virgn',cn_iso_2='VG' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_id='Amerika, Kepulauan Virgin',cn_iso_2='VI' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_id='Vietnam',cn_iso_2='VN' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_id='Vanuatu',cn_iso_2='VU' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_id='Wallis dan Futuna',cn_iso_2='WF' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_id='Samoa',cn_iso_2='WS' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_id='Yaman',cn_iso_2='YE' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_id='Mayotte',cn_iso_2='YT' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_id='Afrika Selatan',cn_iso_2='ZA' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_id='Zambia',cn_iso_2='ZM' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_id='Zimbabwe',cn_iso_2='ZW' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_id='Palestina',cn_iso_2='PS' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_id='Montenegro',cn_iso_2='ME' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_id='Serbia',cn_iso_2='RS' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_id='Kepulauan Aland',cn_iso_2='AX' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_id='Kepulauan Heard dan McDonald',cn_iso_2='HM' WHERE cn_iso_2='HM';


## static_country_zones


## static_currencies
UPDATE static_currencies SET cu_name_id='UAE Dirham',cu_sub_name_id='',cu_iso_3='AED' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_id='Lek',cu_sub_name_id='',cu_iso_3='ALL' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_id='Dram',cu_sub_name_id='',cu_iso_3='AMD' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_id='Niederl. Antillen Gulden',cu_sub_name_id='',cu_iso_3='ANG' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_id='Kwanza',cu_sub_name_id='',cu_iso_3='AOA' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_id='Argentinischer Peso',cu_sub_name_id='',cu_iso_3='ARS' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_id='Australischer Dollar',cu_sub_name_id='',cu_iso_3='AUD' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_id='Aruba Florin',cu_sub_name_id='',cu_iso_3='AWG' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_id='',cu_sub_name_id='',cu_iso_3='AZN' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_id='Konvertierbare Mark',cu_sub_name_id='',cu_iso_3='BAM' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_id='Barbados-Dollar',cu_sub_name_id='',cu_iso_3='BBD' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_id='Taka',cu_sub_name_id='',cu_iso_3='BDT' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_id='Lew',cu_sub_name_id='',cu_iso_3='BGN' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_id='Bahrain-Dinar',cu_sub_name_id='',cu_iso_3='BHD' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_id='Burundi-Franc',cu_sub_name_id='',cu_iso_3='BIF' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_id='Bermuda-Dollar',cu_sub_name_id='',cu_iso_3='BMD' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_id='Brunei-Dollar',cu_sub_name_id='',cu_iso_3='BND' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_id='Boliviano',cu_sub_name_id='',cu_iso_3='BOB' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_id='Real',cu_sub_name_id='',cu_iso_3='BRL' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_id='Bahama-Dollar',cu_sub_name_id='',cu_iso_3='BSD' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_id='Ngultrum',cu_sub_name_id='',cu_iso_3='BTN' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_id='Pula',cu_sub_name_id='',cu_iso_3='BWP' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_id='Belarus Rubel (neu)',cu_sub_name_id='',cu_iso_3='BYR' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_id='Belize-Dollar',cu_sub_name_id='',cu_iso_3='BZD' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_id='Kanadischer Dollar',cu_sub_name_id='',cu_iso_3='CAD' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_id='Franc congolais',cu_sub_name_id='',cu_iso_3='CDF' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_id='Schweizer Franken',cu_sub_name_id='',cu_iso_3='CHF' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_id='Chilenischer Peso',cu_sub_name_id='',cu_iso_3='CLP' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_id='Renminbi Yuan',cu_sub_name_id='',cu_iso_3='CNY' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_id='Kolumbianischer Peso',cu_sub_name_id='',cu_iso_3='COP' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_id='Costa Rica Colon',cu_sub_name_id='',cu_iso_3='CRC' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_id='Kubanischer Peso',cu_sub_name_id='',cu_iso_3='CUP' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_id='Kap Verde Escudo',cu_sub_name_id='',cu_iso_3='CVE' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_id='Zypern Pfund',cu_sub_name_id='',cu_iso_3='CYP' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_id='Tschechische Krone',cu_sub_name_id='',cu_iso_3='CZK' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_id='Dschibuti-Franc',cu_sub_name_id='',cu_iso_3='DJF' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_id='Dänische Krone',cu_sub_name_id='',cu_iso_3='DKK' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_id='Dominikanischer Peso',cu_sub_name_id='',cu_iso_3='DOP' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_id='Algerischer Dinar',cu_sub_name_id='',cu_iso_3='DZD' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_id='Estnische Krone',cu_sub_name_id='',cu_iso_3='EEK' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_id='Ägyptisches Pfund',cu_sub_name_id='',cu_iso_3='EGP' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_id='Nakfa',cu_sub_name_id='',cu_iso_3='ERN' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_id='Birr',cu_sub_name_id='',cu_iso_3='ETB' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_id='Euro',cu_sub_name_id='',cu_iso_3='EUR' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_id='Fidschi Dollar',cu_sub_name_id='',cu_iso_3='FJD' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_id='Falkland Pfund',cu_sub_name_id='',cu_iso_3='FKP' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_id='Pfund Sterling',cu_sub_name_id='',cu_iso_3='GBP' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_id='Georgischer Lari',cu_sub_name_id='',cu_iso_3='GEL' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_id='Cedi',cu_sub_name_id='',cu_iso_3='GHC' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_id='Gibraltar Pfund',cu_sub_name_id='',cu_iso_3='GIP' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_id='Dalasi',cu_sub_name_id='',cu_iso_3='GMD' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_id='Guinea Franc',cu_sub_name_id='',cu_iso_3='GNF' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_id='Quetzal',cu_sub_name_id='',cu_iso_3='GTQ' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_id='Guinea Bissau Peso',cu_sub_name_id='',cu_iso_3='GWP' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_id='Guyana Dollar',cu_sub_name_id='',cu_iso_3='GYD' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_id='Hongkong Dollar',cu_sub_name_id='',cu_iso_3='HKD' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_id='Lempira',cu_sub_name_id='',cu_iso_3='HNL' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_id='Kuna',cu_sub_name_id='',cu_iso_3='HRK' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_id='Gourde',cu_sub_name_id='',cu_iso_3='HTG' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_id='Forint',cu_sub_name_id='',cu_iso_3='HUF' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_id='Rupiah',cu_sub_name_id='',cu_iso_3='IDR' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_id='Schekel',cu_sub_name_id='',cu_iso_3='ILS' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_id='Indische Rupie',cu_sub_name_id='',cu_iso_3='INR' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_id='Irak Dinar',cu_sub_name_id='',cu_iso_3='IQD' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_id='Rial',cu_sub_name_id='',cu_iso_3='IRR' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_id='Isländische Krone',cu_sub_name_id='',cu_iso_3='ISK' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_id='Jamaika Dollar',cu_sub_name_id='',cu_iso_3='JMD' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_id='Jordanischer Dinar',cu_sub_name_id='',cu_iso_3='JOD' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_id='Yen',cu_sub_name_id='',cu_iso_3='JPY' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_id='Kenia Schilling',cu_sub_name_id='',cu_iso_3='KES' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_id='Som',cu_sub_name_id='',cu_iso_3='KGS' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_id='Riel',cu_sub_name_id='',cu_iso_3='KHR' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_id='Komoren Franc',cu_sub_name_id='',cu_iso_3='KMF' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_id='Nordkoreanischer Won',cu_sub_name_id='',cu_iso_3='KPW' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_id='Südkoreanischer Won',cu_sub_name_id='',cu_iso_3='KRW' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_id='Kuwait Dinar',cu_sub_name_id='',cu_iso_3='KWD' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_id='Kaiman-Dollar',cu_sub_name_id='',cu_iso_3='KYD' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_id='Tenge',cu_sub_name_id='',cu_iso_3='KZT' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_id='Kip',cu_sub_name_id='',cu_iso_3='LAK' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_id='Libanesisches Pfund',cu_sub_name_id='',cu_iso_3='LBP' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_id='Sri Lanka Rupie',cu_sub_name_id='',cu_iso_3='LKR' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_id='Liberianischer Dollar',cu_sub_name_id='',cu_iso_3='LRD' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_id='Loti',cu_sub_name_id='',cu_iso_3='LSL' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_id='Litauischer Litas',cu_sub_name_id='',cu_iso_3='LTL' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_id='Lettischer Lats',cu_sub_name_id='',cu_iso_3='LVL' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_id='Libyscher Dinar',cu_sub_name_id='',cu_iso_3='LYD' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_id='Marokkanischer Dirham',cu_sub_name_id='',cu_iso_3='MAD' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_id='Moldau Leu',cu_sub_name_id='',cu_iso_3='MDL' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_id='Denar',cu_sub_name_id='',cu_iso_3='MKD' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_id='Kyat',cu_sub_name_id='',cu_iso_3='MMK' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_id='Tugrik',cu_sub_name_id='',cu_iso_3='MNT' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_id='Pataca',cu_sub_name_id='',cu_iso_3='MOP' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_id='Ouguiya',cu_sub_name_id='',cu_iso_3='MRO' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_id='Maltesische Lira',cu_sub_name_id='',cu_iso_3='MTL' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_id='Mauritius Rupie',cu_sub_name_id='',cu_iso_3='MUR' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_id='Rufiyaa',cu_sub_name_id='',cu_iso_3='MVR' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_id='Malawi Kwacha',cu_sub_name_id='',cu_iso_3='MWK' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_id='Mexikanischer Peso',cu_sub_name_id='',cu_iso_3='MXN' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_id='Malaysischer Ringgit',cu_sub_name_id='',cu_iso_3='MYR' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_id='Metical',cu_sub_name_id='',cu_iso_3='MZM' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_id='Namibia Dollar',cu_sub_name_id='',cu_iso_3='NAD' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_id='Naira',cu_sub_name_id='',cu_iso_3='NGN' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_id='Gold-Cordoba',cu_sub_name_id='',cu_iso_3='NIO' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_id='Norwegische Krone',cu_sub_name_id='',cu_iso_3='NOK' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_id='Nepalesische Rupie',cu_sub_name_id='',cu_iso_3='NPR' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_id='Neuseeland Dollar',cu_sub_name_id='',cu_iso_3='NZD' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_id='Rial Omani',cu_sub_name_id='',cu_iso_3='OMR' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_id='Balboa',cu_sub_name_id='',cu_iso_3='PAB' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_id='Neuer Sol',cu_sub_name_id='',cu_iso_3='PEN' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_id='Kina',cu_sub_name_id='',cu_iso_3='PGK' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_id='Philippinischer Peso',cu_sub_name_id='',cu_iso_3='PHP' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_id='Pakistanische Rupie',cu_sub_name_id='',cu_iso_3='PKR' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_id='Zloty',cu_sub_name_id='',cu_iso_3='PLN' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_id='Guarani',cu_sub_name_id='',cu_iso_3='PYG' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_id='Katar Riyal',cu_sub_name_id='',cu_iso_3='QAR' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_id='Leu',cu_sub_name_id='',cu_iso_3='ROL' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_id='Russischer Rubel (neu)',cu_sub_name_id='',cu_iso_3='RUB' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_id='Ruanda Franc',cu_sub_name_id='',cu_iso_3='RWF' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_id='Saudi Riyal',cu_sub_name_id='',cu_iso_3='SAR' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_id='Salomonen Dollar',cu_sub_name_id='',cu_iso_3='SBD' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_id='Seychellen Rupie',cu_sub_name_id='',cu_iso_3='SCR' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_id='',cu_sub_name_id='',cu_iso_3='SDG' WHERE cu_iso_3='SDG';
UPDATE static_currencies SET cu_name_id='Schwedische Krone',cu_sub_name_id='',cu_iso_3='SEK' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_id='Singapur Dollar',cu_sub_name_id='',cu_iso_3='SGD' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_id='St. Helena Pfund',cu_sub_name_id='',cu_iso_3='SHP' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_id='Tolar',cu_sub_name_id='',cu_iso_3='SIT' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_id='Slowakische Krone',cu_sub_name_id='',cu_iso_3='SKK' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_id='Leone',cu_sub_name_id='',cu_iso_3='SLL' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_id='Somalia Schilling',cu_sub_name_id='',cu_iso_3='SOS' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_id='Dobra',cu_sub_name_id='',cu_iso_3='STD' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_id='El Salvador Colon',cu_sub_name_id='',cu_iso_3='SVC' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_id='Syrisches Pfund',cu_sub_name_id='',cu_iso_3='SYP' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_id='Lilangeni',cu_sub_name_id='',cu_iso_3='SZL' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_id='Baht',cu_sub_name_id='',cu_iso_3='THB' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_id='Tadschikistan Somoni',cu_sub_name_id='',cu_iso_3='TJS' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_id='Turkmenistan-Manat',cu_sub_name_id='',cu_iso_3='TMM' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_id='Tunesischer Dinar',cu_sub_name_id='',cu_iso_3='TND' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_id='Pa?anga',cu_sub_name_id='',cu_iso_3='TOP' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_id='Trinidad und Tobago Dollar',cu_sub_name_id='',cu_iso_3='TTD' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_id='Neuer Taiwan Dollar',cu_sub_name_id='',cu_iso_3='TWD' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_id='Tansania Schilling',cu_sub_name_id='',cu_iso_3='TZS' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_id='Hryvnia',cu_sub_name_id='',cu_iso_3='UAH' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_id='Uganda Schilling',cu_sub_name_id='',cu_iso_3='UGX' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_id='US Dollar',cu_sub_name_id='',cu_iso_3='USD' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_id='Uruguayischer Peso',cu_sub_name_id='',cu_iso_3='UYU' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_id='Usbekistan Sum',cu_sub_name_id='',cu_iso_3='UZS' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_id='Bolivar',cu_sub_name_id='',cu_iso_3='VEB' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_id='Dong',cu_sub_name_id='',cu_iso_3='VND' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_id='Vatu',cu_sub_name_id='',cu_iso_3='VUV' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_id='Tala',cu_sub_name_id='',cu_iso_3='WST' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_id='CFA Franc (Äquatorial)',cu_sub_name_id='',cu_iso_3='XAF' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_id='Ostkaribischer Dollar',cu_sub_name_id='',cu_iso_3='XCD' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_id='CFA Franc (West)',cu_sub_name_id='',cu_iso_3='XOF' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_id='CFP Franc',cu_sub_name_id='',cu_iso_3='XPF' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_id='Jemen Rial',cu_sub_name_id='',cu_iso_3='YER' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_id='Rand',cu_sub_name_id='',cu_iso_3='ZAR' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_id='Kwacha',cu_sub_name_id='',cu_iso_3='ZMK' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_id='Simbabwe Dollar',cu_sub_name_id='',cu_iso_3='ZWD' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_id='Afghani',cu_sub_name_id='',cu_iso_3='AFN' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_id='',cu_sub_name_id='',cu_iso_3='CSD' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_id='Madagaskar Ariary',cu_sub_name_id='',cu_iso_3='MGA' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_id='',cu_sub_name_id='',cu_iso_3='SRD' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_id='Neue Türkische Lira',cu_sub_name_id='',cu_iso_3='TRY' WHERE cu_iso_3='TRY';
UPDATE static_currencies SET cu_name_id='',cu_sub_name_id='',cu_iso_3='SSP' WHERE cu_iso_3='SSP';


## static_languages
UPDATE static_languages SET lg_name_id='Abchasisch',lg_iso_2='AB' WHERE lg_iso_2='AB';
UPDATE static_languages SET lg_name_id='Afar',lg_iso_2='AA' WHERE lg_iso_2='AA';
UPDATE static_languages SET lg_name_id='Afrikaans',lg_iso_2='AF' WHERE lg_iso_2='AF';
UPDATE static_languages SET lg_name_id='Albanisch',lg_iso_2='SQ' WHERE lg_iso_2='SQ';
UPDATE static_languages SET lg_name_id='Amharisch',lg_iso_2='AM' WHERE lg_iso_2='AM';
UPDATE static_languages SET lg_name_id='Arabisch',lg_iso_2='AR' WHERE lg_iso_2='AR';
UPDATE static_languages SET lg_name_id='Armenisch',lg_iso_2='HY' WHERE lg_iso_2='HY';
UPDATE static_languages SET lg_name_id='Assamesisch',lg_iso_2='AS' WHERE lg_iso_2='AS';
UPDATE static_languages SET lg_name_id='Aymará-Sprache',lg_iso_2='AY' WHERE lg_iso_2='AY';
UPDATE static_languages SET lg_name_id='Aserbaidschanisch',lg_iso_2='AZ' WHERE lg_iso_2='AZ';
UPDATE static_languages SET lg_name_id='Baschkirisch',lg_iso_2='BA' WHERE lg_iso_2='BA';
UPDATE static_languages SET lg_name_id='Baskisch',lg_iso_2='EU' WHERE lg_iso_2='EU';
UPDATE static_languages SET lg_name_id='Bengalisch',lg_iso_2='BN' WHERE lg_iso_2='BN';
UPDATE static_languages SET lg_name_id='Bhutanisch',lg_iso_2='DZ' WHERE lg_iso_2='DZ';
UPDATE static_languages SET lg_name_id='Biharisch',lg_iso_2='BH' WHERE lg_iso_2='BH';
UPDATE static_languages SET lg_name_id='Bislama',lg_iso_2='BI' WHERE lg_iso_2='BI';
UPDATE static_languages SET lg_name_id='Bretonisch',lg_iso_2='BR' WHERE lg_iso_2='BR';
UPDATE static_languages SET lg_name_id='Bulgarisch',lg_iso_2='BG' WHERE lg_iso_2='BG';
UPDATE static_languages SET lg_name_id='Birmanisch',lg_iso_2='MY' WHERE lg_iso_2='MY';
UPDATE static_languages SET lg_name_id='Weißrussisch',lg_iso_2='BE' WHERE lg_iso_2='BE';
UPDATE static_languages SET lg_name_id='Kambodschanisch',lg_iso_2='KM' WHERE lg_iso_2='KM';
UPDATE static_languages SET lg_name_id='Katalanisch',lg_iso_2='CA' WHERE lg_iso_2='CA';
UPDATE static_languages SET lg_name_id='Zhuang',lg_iso_2='ZA' WHERE lg_iso_2='ZA';
UPDATE static_languages SET lg_name_id='Chinesisch',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_id='Korsisch',lg_iso_2='CO' WHERE lg_iso_2='CO';
UPDATE static_languages SET lg_name_id='Kroatisch',lg_iso_2='HR' WHERE lg_iso_2='HR';
UPDATE static_languages SET lg_name_id='Tschechisch',lg_iso_2='CS' WHERE lg_iso_2='CS';
UPDATE static_languages SET lg_name_id='Dänisch',lg_iso_2='DA' WHERE lg_iso_2='DA';
UPDATE static_languages SET lg_name_id='Niederländisch',lg_iso_2='NL' WHERE lg_iso_2='NL';
UPDATE static_languages SET lg_name_id='Englisch',lg_iso_2='EN' WHERE lg_iso_2='EN';
UPDATE static_languages SET lg_name_id='Esperanto',lg_iso_2='EO' WHERE lg_iso_2='EO';
UPDATE static_languages SET lg_name_id='Estnisch',lg_iso_2='ET' WHERE lg_iso_2='ET';
UPDATE static_languages SET lg_name_id='Färöisch',lg_iso_2='FO' WHERE lg_iso_2='FO';
UPDATE static_languages SET lg_name_id='Persisch',lg_iso_2='FA' WHERE lg_iso_2='FA';
UPDATE static_languages SET lg_name_id='Fidschianisch',lg_iso_2='FJ' WHERE lg_iso_2='FJ';
UPDATE static_languages SET lg_name_id='Finnisch',lg_iso_2='FI' WHERE lg_iso_2='FI';
UPDATE static_languages SET lg_name_id='Französisch',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_id='Friesisch',lg_iso_2='FY' WHERE lg_iso_2='FY';
UPDATE static_languages SET lg_name_id='Galizisch',lg_iso_2='GL' WHERE lg_iso_2='GL';
UPDATE static_languages SET lg_name_id='Schottisch-Gälisch',lg_iso_2='GD' WHERE lg_iso_2='GD';
UPDATE static_languages SET lg_name_id='Manx',lg_iso_2='GV' WHERE lg_iso_2='GV';
UPDATE static_languages SET lg_name_id='Georgisch',lg_iso_2='KA' WHERE lg_iso_2='KA';
UPDATE static_languages SET lg_name_id='Deutsch',lg_iso_2='DE' WHERE lg_iso_2='DE';
UPDATE static_languages SET lg_name_id='Griechisch',lg_iso_2='EL' WHERE lg_iso_2='EL';
UPDATE static_languages SET lg_name_id='Grönländisch',lg_iso_2='KL' WHERE lg_iso_2='KL';
UPDATE static_languages SET lg_name_id='Guarani',lg_iso_2='GN' WHERE lg_iso_2='GN';
UPDATE static_languages SET lg_name_id='Gujarati',lg_iso_2='GU' WHERE lg_iso_2='GU';
UPDATE static_languages SET lg_name_id='Hausa',lg_iso_2='HA' WHERE lg_iso_2='HA';
UPDATE static_languages SET lg_name_id='Hebräisch',lg_iso_2='HE' WHERE lg_iso_2='HE';
UPDATE static_languages SET lg_name_id='Hindi',lg_iso_2='HI' WHERE lg_iso_2='HI';
UPDATE static_languages SET lg_name_id='Ungarisch',lg_iso_2='HU' WHERE lg_iso_2='HU';
UPDATE static_languages SET lg_name_id='Isländisch',lg_iso_2='IS' WHERE lg_iso_2='IS';
UPDATE static_languages SET lg_name_id='Indonesisch',lg_iso_2='ID' WHERE lg_iso_2='ID';
UPDATE static_languages SET lg_name_id='Interlingua',lg_iso_2='IA' WHERE lg_iso_2='IA';
UPDATE static_languages SET lg_name_id='Interlingue',lg_iso_2='IE' WHERE lg_iso_2='IE';
UPDATE static_languages SET lg_name_id='Inukitut',lg_iso_2='IU' WHERE lg_iso_2='IU';
UPDATE static_languages SET lg_name_id='Inupiak',lg_iso_2='IK' WHERE lg_iso_2='IK';
UPDATE static_languages SET lg_name_id='Irisch',lg_iso_2='GA' WHERE lg_iso_2='GA';
UPDATE static_languages SET lg_name_id='Italienisch',lg_iso_2='IT' WHERE lg_iso_2='IT';
UPDATE static_languages SET lg_name_id='Japanisch',lg_iso_2='JA' WHERE lg_iso_2='JA';
UPDATE static_languages SET lg_name_id='Kannada',lg_iso_2='KN' WHERE lg_iso_2='KN';
UPDATE static_languages SET lg_name_id='Kaschmirisch',lg_iso_2='KS' WHERE lg_iso_2='KS';
UPDATE static_languages SET lg_name_id='Kasachisch',lg_iso_2='KK' WHERE lg_iso_2='KK';
UPDATE static_languages SET lg_name_id='Ruandisch',lg_iso_2='RW' WHERE lg_iso_2='RW';
UPDATE static_languages SET lg_name_id='Kirgisisch',lg_iso_2='KY' WHERE lg_iso_2='KY';
UPDATE static_languages SET lg_name_id='Rundi-Sprache',lg_iso_2='RN' WHERE lg_iso_2='RN';
UPDATE static_languages SET lg_name_id='Koreanisch',lg_iso_2='KO' WHERE lg_iso_2='KO';
UPDATE static_languages SET lg_name_id='Kurdisch',lg_iso_2='KU' WHERE lg_iso_2='KU';
UPDATE static_languages SET lg_name_id='Laotisch',lg_iso_2='LO' WHERE lg_iso_2='LO';
UPDATE static_languages SET lg_name_id='Latein',lg_iso_2='LA' WHERE lg_iso_2='LA';
UPDATE static_languages SET lg_name_id='Lettisch',lg_iso_2='LV' WHERE lg_iso_2='LV';
UPDATE static_languages SET lg_name_id='Lingala',lg_iso_2='LN' WHERE lg_iso_2='LN';
UPDATE static_languages SET lg_name_id='Litauisch',lg_iso_2='LT' WHERE lg_iso_2='LT';
UPDATE static_languages SET lg_name_id='Mazedonisch',lg_iso_2='MK' WHERE lg_iso_2='MK';
UPDATE static_languages SET lg_name_id='Madagassisch',lg_iso_2='MG' WHERE lg_iso_2='MG';
UPDATE static_languages SET lg_name_id='Malaiisch',lg_iso_2='MS' WHERE lg_iso_2='MS';
UPDATE static_languages SET lg_name_id='Malayalam',lg_iso_2='ML' WHERE lg_iso_2='ML';
UPDATE static_languages SET lg_name_id='Maltesisch',lg_iso_2='MT' WHERE lg_iso_2='MT';
UPDATE static_languages SET lg_name_id='Maori',lg_iso_2='MI' WHERE lg_iso_2='MI';
UPDATE static_languages SET lg_name_id='Marathi',lg_iso_2='MR' WHERE lg_iso_2='MR';
UPDATE static_languages SET lg_name_id='Moldauisch',lg_iso_2='MO' WHERE lg_iso_2='MO';
UPDATE static_languages SET lg_name_id='Mongolisch',lg_iso_2='MN' WHERE lg_iso_2='MN';
UPDATE static_languages SET lg_name_id='Nauruisch',lg_iso_2='NA' WHERE lg_iso_2='NA';
UPDATE static_languages SET lg_name_id='Nepalesisch',lg_iso_2='NE' WHERE lg_iso_2='NE';
UPDATE static_languages SET lg_name_id='Norwegisch',lg_iso_2='NO' WHERE lg_iso_2='NO';
UPDATE static_languages SET lg_name_id='Okzitanisch',lg_iso_2='OC' WHERE lg_iso_2='OC';
UPDATE static_languages SET lg_name_id='Orija',lg_iso_2='OR' WHERE lg_iso_2='OR';
UPDATE static_languages SET lg_name_id='Oromo',lg_iso_2='OM' WHERE lg_iso_2='OM';
UPDATE static_languages SET lg_name_id='Afghanisch (Paschtu)',lg_iso_2='PS' WHERE lg_iso_2='PS';
UPDATE static_languages SET lg_name_id='Polnisch',lg_iso_2='PL' WHERE lg_iso_2='PL';
UPDATE static_languages SET lg_name_id='Portugiesisch',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_id='Pandschabisch',lg_iso_2='PA' WHERE lg_iso_2='PA';
UPDATE static_languages SET lg_name_id='Quechua',lg_iso_2='QU' WHERE lg_iso_2='QU';
UPDATE static_languages SET lg_name_id='Rätoromanisch',lg_iso_2='RM' WHERE lg_iso_2='RM';
UPDATE static_languages SET lg_name_id='Rumänisch',lg_iso_2='RO' WHERE lg_iso_2='RO';
UPDATE static_languages SET lg_name_id='Russisch',lg_iso_2='RU' WHERE lg_iso_2='RU';
UPDATE static_languages SET lg_name_id='Samoanisch',lg_iso_2='SM' WHERE lg_iso_2='SM';
UPDATE static_languages SET lg_name_id='Sango',lg_iso_2='SG' WHERE lg_iso_2='SG';
UPDATE static_languages SET lg_name_id='Sanskrit',lg_iso_2='SA' WHERE lg_iso_2='SA';
UPDATE static_languages SET lg_name_id='Serbisch',lg_iso_2='SR' WHERE lg_iso_2='SR';
UPDATE static_languages SET lg_name_id='Süd-Sotho-Sprache',lg_iso_2='ST' WHERE lg_iso_2='ST';
UPDATE static_languages SET lg_name_id='Tswana-Sprache',lg_iso_2='TN' WHERE lg_iso_2='TN';
UPDATE static_languages SET lg_name_id='Shona',lg_iso_2='SN' WHERE lg_iso_2='SN';
UPDATE static_languages SET lg_name_id='Sindhi',lg_iso_2='SD' WHERE lg_iso_2='SD';
UPDATE static_languages SET lg_name_id='Singhalesisch',lg_iso_2='SI' WHERE lg_iso_2='SI';
UPDATE static_languages SET lg_name_id='Swazi',lg_iso_2='SS' WHERE lg_iso_2='SS';
UPDATE static_languages SET lg_name_id='Slowakisch',lg_iso_2='SK' WHERE lg_iso_2='SK';
UPDATE static_languages SET lg_name_id='Slowenisch',lg_iso_2='SL' WHERE lg_iso_2='SL';
UPDATE static_languages SET lg_name_id='Somali',lg_iso_2='SO' WHERE lg_iso_2='SO';
UPDATE static_languages SET lg_name_id='Spanisch',lg_iso_2='ES' WHERE lg_iso_2='ES';
UPDATE static_languages SET lg_name_id='Sudanesisch',lg_iso_2='SU' WHERE lg_iso_2='SU';
UPDATE static_languages SET lg_name_id='Suaheli',lg_iso_2='SW' WHERE lg_iso_2='SW';
UPDATE static_languages SET lg_name_id='Schwedisch',lg_iso_2='SV' WHERE lg_iso_2='SV';
UPDATE static_languages SET lg_name_id='Tagalog',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_id='Tadschikisch',lg_iso_2='TG' WHERE lg_iso_2='TG';
UPDATE static_languages SET lg_name_id='Tamilisch',lg_iso_2='TA' WHERE lg_iso_2='TA';
UPDATE static_languages SET lg_name_id='Tatarisch',lg_iso_2='TT' WHERE lg_iso_2='TT';
UPDATE static_languages SET lg_name_id='Telugu',lg_iso_2='TE' WHERE lg_iso_2='TE';
UPDATE static_languages SET lg_name_id='Thai',lg_iso_2='TH' WHERE lg_iso_2='TH';
UPDATE static_languages SET lg_name_id='Tibetisch',lg_iso_2='BO' WHERE lg_iso_2='BO';
UPDATE static_languages SET lg_name_id='Tigrinja',lg_iso_2='TI' WHERE lg_iso_2='TI';
UPDATE static_languages SET lg_name_id='Tongaisch',lg_iso_2='TO' WHERE lg_iso_2='TO';
UPDATE static_languages SET lg_name_id='Tsonga',lg_iso_2='TS' WHERE lg_iso_2='TS';
UPDATE static_languages SET lg_name_id='Türkisch',lg_iso_2='TR' WHERE lg_iso_2='TR';
UPDATE static_languages SET lg_name_id='Turkmenisch',lg_iso_2='TK' WHERE lg_iso_2='TK';
UPDATE static_languages SET lg_name_id='Twi',lg_iso_2='TW' WHERE lg_iso_2='TW';
UPDATE static_languages SET lg_name_id='Uigurisch',lg_iso_2='UG' WHERE lg_iso_2='UG';
UPDATE static_languages SET lg_name_id='Ukrainisch',lg_iso_2='UK' WHERE lg_iso_2='UK';
UPDATE static_languages SET lg_name_id='Urdu',lg_iso_2='UR' WHERE lg_iso_2='UR';
UPDATE static_languages SET lg_name_id='Usbekisch',lg_iso_2='UZ' WHERE lg_iso_2='UZ';
UPDATE static_languages SET lg_name_id='Vietnamesisch',lg_iso_2='VI' WHERE lg_iso_2='VI';
UPDATE static_languages SET lg_name_id='Volapük',lg_iso_2='VO' WHERE lg_iso_2='VO';
UPDATE static_languages SET lg_name_id='Kymrisch',lg_iso_2='CY' WHERE lg_iso_2='CY';
UPDATE static_languages SET lg_name_id='Wolof',lg_iso_2='WO' WHERE lg_iso_2='WO';
UPDATE static_languages SET lg_name_id='Xhosa',lg_iso_2='XH' WHERE lg_iso_2='XH';
UPDATE static_languages SET lg_name_id='Jiddisch',lg_iso_2='YI' WHERE lg_iso_2='YI';
UPDATE static_languages SET lg_name_id='Joruba',lg_iso_2='YO' WHERE lg_iso_2='YO';
UPDATE static_languages SET lg_name_id='Zulu',lg_iso_2='ZU' WHERE lg_iso_2='ZU';
UPDATE static_languages SET lg_name_id='Bosnisch',lg_iso_2='BS' WHERE lg_iso_2='BS';
UPDATE static_languages SET lg_name_id='Avestisch',lg_iso_2='AE' WHERE lg_iso_2='AE';
UPDATE static_languages SET lg_name_id='Akan',lg_iso_2='AK' WHERE lg_iso_2='AK';
UPDATE static_languages SET lg_name_id='Aragonesisch',lg_iso_2='AN' WHERE lg_iso_2='AN';
UPDATE static_languages SET lg_name_id='Awarisch',lg_iso_2='AV' WHERE lg_iso_2='AV';
UPDATE static_languages SET lg_name_id='Bambara-Sprache',lg_iso_2='BM' WHERE lg_iso_2='BM';
UPDATE static_languages SET lg_name_id='Tschetschenisch',lg_iso_2='CE' WHERE lg_iso_2='CE';
UPDATE static_languages SET lg_name_id='Chamorro-Sprache',lg_iso_2='CH' WHERE lg_iso_2='CH';
UPDATE static_languages SET lg_name_id='Cree',lg_iso_2='CR' WHERE lg_iso_2='CR';
UPDATE static_languages SET lg_name_id='Kirchenslawisch',lg_iso_2='CU' WHERE lg_iso_2='CU';
UPDATE static_languages SET lg_name_id='Tschuwaschisch',lg_iso_2='CV' WHERE lg_iso_2='CV';
UPDATE static_languages SET lg_name_id='Maledivisch',lg_iso_2='DV' WHERE lg_iso_2='DV';
UPDATE static_languages SET lg_name_id='Ewe-Sprache',lg_iso_2='EE' WHERE lg_iso_2='EE';
UPDATE static_languages SET lg_name_id='Ful',lg_iso_2='FF' WHERE lg_iso_2='FF';
UPDATE static_languages SET lg_name_id='Hiri-Motu',lg_iso_2='HO' WHERE lg_iso_2='HO';
UPDATE static_languages SET lg_name_id='Kreolisch',lg_iso_2='HT' WHERE lg_iso_2='HT';
UPDATE static_languages SET lg_name_id='Herero-Sprache',lg_iso_2='HZ' WHERE lg_iso_2='HZ';
UPDATE static_languages SET lg_name_id='Igbo-Sprache',lg_iso_2='IG' WHERE lg_iso_2='IG';
UPDATE static_languages SET lg_name_id='Sichuan Yi',lg_iso_2='II' WHERE lg_iso_2='II';
UPDATE static_languages SET lg_name_id='Ido-Sprache',lg_iso_2='IO' WHERE lg_iso_2='IO';
UPDATE static_languages SET lg_name_id='Javanisch',lg_iso_2='JV' WHERE lg_iso_2='JV';
UPDATE static_languages SET lg_name_id='Kongo',lg_iso_2='KG' WHERE lg_iso_2='KG';
UPDATE static_languages SET lg_name_id='Kikuyu-Sprache',lg_iso_2='KI' WHERE lg_iso_2='KI';
UPDATE static_languages SET lg_name_id='Kwanyama',lg_iso_2='KJ' WHERE lg_iso_2='KJ';
UPDATE static_languages SET lg_name_id='Kanuri-Sprache',lg_iso_2='KR' WHERE lg_iso_2='KR';
UPDATE static_languages SET lg_name_id='Komi-Sprache',lg_iso_2='KV' WHERE lg_iso_2='KV';
UPDATE static_languages SET lg_name_id='Kornisch',lg_iso_2='KW' WHERE lg_iso_2='KW';
UPDATE static_languages SET lg_name_id='Luxemburgisch',lg_iso_2='LB' WHERE lg_iso_2='LB';
UPDATE static_languages SET lg_name_id='Ganda-Sprache',lg_iso_2='LG' WHERE lg_iso_2='LG';
UPDATE static_languages SET lg_name_id='Limburgisch',lg_iso_2='LI' WHERE lg_iso_2='LI';
UPDATE static_languages SET lg_name_id='Luba',lg_iso_2='LU' WHERE lg_iso_2='LU';
UPDATE static_languages SET lg_name_id='Marschallesisch',lg_iso_2='MH' WHERE lg_iso_2='MH';
UPDATE static_languages SET lg_name_id='Norwegisch Bokmål',lg_iso_2='NB' WHERE lg_iso_2='NB';
UPDATE static_languages SET lg_name_id='Ndebele-Sprache (Nord)',lg_iso_2='ND' WHERE lg_iso_2='ND';
UPDATE static_languages SET lg_name_id='Ndonga',lg_iso_2='NG' WHERE lg_iso_2='NG';
UPDATE static_languages SET lg_name_id='Norwegisch Nynorsk',lg_iso_2='NN' WHERE lg_iso_2='NN';
UPDATE static_languages SET lg_name_id='Ndebele-Sprache (Süd)',lg_iso_2='NR' WHERE lg_iso_2='NR';
UPDATE static_languages SET lg_name_id='Navajo-Sprache',lg_iso_2='NV' WHERE lg_iso_2='NV';
UPDATE static_languages SET lg_name_id='Chewa-Sprache',lg_iso_2='NY' WHERE lg_iso_2='NY';
UPDATE static_languages SET lg_name_id='Ojibwa-Sprache',lg_iso_2='OJ' WHERE lg_iso_2='OJ';
UPDATE static_languages SET lg_name_id='Ossetisch',lg_iso_2='OS' WHERE lg_iso_2='OS';
UPDATE static_languages SET lg_name_id='Pali',lg_iso_2='PI' WHERE lg_iso_2='PI';
UPDATE static_languages SET lg_name_id='Sardisch',lg_iso_2='SC' WHERE lg_iso_2='SC';
UPDATE static_languages SET lg_name_id='Nord-Samisch',lg_iso_2='SE' WHERE lg_iso_2='SE';
UPDATE static_languages SET lg_name_id='Tahitisch',lg_iso_2='TY' WHERE lg_iso_2='TY';
UPDATE static_languages SET lg_name_id='Venda-Sprache',lg_iso_2='VE' WHERE lg_iso_2='VE';
UPDATE static_languages SET lg_name_id='Wallonisch',lg_iso_2='WA' WHERE lg_iso_2='WA';
UPDATE static_languages SET lg_name_id='Portugiesisch',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_id='Chinesisch',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_id='',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_id='',lg_iso_2='TL' WHERE lg_iso_2='TL';


